# Generated by Django 5.2 on 2025-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_full_name_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Computer Science'), (3, 'Electrical Engineering'), (4, 'Mechanical Engineering'), (5, 'Civil Engineering'), (6, 'Chemical Engineering'), (7, 'Software Engineering'), (8, 'Information Technology'), (9, 'Business Administration'), (10, 'Economics'), (11, 'Mathematics'), (12, 'Physics'), (13, 'Chemistry'), (14, 'Biology'), (15, 'English'), (16, 'Psychology'), (17, 'Sociology'), (18, 'Education'), (19, 'Architecture'), (20, 'Law'), (21, 'Pharmacy'), (22, 'Medical Sciences'), (23, 'Islamic Studies'), (24, 'Environmental Science')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
